# Generated by Django 5.1.2 on 2024-11-30 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_order_datetime_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='datetime_created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
